Secrets/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^secrets/', include('apps.secrets.urls', namespace='secrets')),
]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/secrets/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
    url(r'^post_secret$', views.post_secret, name='post_secret'),
    url(r'^popular$', views.popular, name='popular'),
    url(r'^(?P<id>\d+)/like$', views.like, name='like'),
    url(r'^(?P<id>\d+)/delete$', views.delete, name='delete'),
]

apps/secrets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.db.models import Count
from ..login.models import User

class SecretManager(models.Manager):
    def new_secret(self, *data):
        if len(data[0]) >0:
            self.create(secret = data[0], user_id = User.objects.get(email = data[1]))
            return True
        else:
            return False
    def popular(self):
        return self.annotate(num_likes=Count('secret_like')).order_by('num_likes').reverse()

    def recent(self):
        return self.all().order_by('created_at').reverse()[:5]

class LikeManager(models.Manager):
    def liked(self, *data):
        self.create(user_id=User.objects.get(email=data[0]), secret_id=Secret.objects.get(id=data[1]))

class Secret(models.Model):
    secret = models.TextField()
    user_id = models.ForeignKey(User, related_name='secret')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = SecretManager()

    # this will return all User objects for the secret passed in
    def secretlikes(self):
        return User.objects.filter(user_like__secret_id=self)


class Like(models.Model):
    user_id = models.ForeignKey(User, related_name='user_like')
    secret_id = models.ForeignKey(Secret, related_name='secret_like')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = LikeManager()

apps/secrets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import Count
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Secret, Like, User

def welcome(request):
    if 'user' in request.session:
        print "Logged in user is", request.session['user']['name']
        user = User.objects.get(email = request.session['user']['email'])
        secrets = Secret.objects.recent()
        context = {
            'user': user,
            'secrets': secrets,
        }
        return render(request, 'secrets/index.html', context)
    return redirect('login:index')

def post_secret(request):
    if request.method == 'POST':
        print 'Attempting to check and then add secret by User Email'
        posted = Secret.objects.new_secret(request.POST['secret'], request.session['user']['email'])
        if posted:
            print 'Success, the secret was posted'
            return redirect('secrets:welcome')
        elif not posted:
            print 'Did not post'
            messages.add_message(request, messages.ERROR, 'Please post a message.')
            return redirect('secrets:welcome')
    return redirect('secrets:welcome')

def popular(request):
    user = User.objects.get(email = request.session['user']['email'])
    secrets = Secret.objects.popular()
    context = {
        'user': user,
        'secrets': secrets,
    }
    return render(request, 'secrets/popular.html', context)

def like(request, id):
    liked = Like.objects.liked(request.session['user']['email'],id)
    print 'Liked'
    return redirect('secrets:welcome')

def delete(request, id):
    secret = Secret.objects.get(id = id)
    print secret
    deleted = secret.delete()
    print deleted
    return redirect('secrets:welcome')

apps/secrets/templates/secrets/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Secrets</title>
  </head>
  <body>
    <h1>Hello, {{user.first_name}}!</h1>
    <a href="{% url 'login:logout' %}">Logout</a>
    <form class="" action="{% url 'secrets:post_secret' %}" method="post">
      {% csrf_token %}
      <textarea name="secret" rows="8" cols="80"></textarea>
      <br>
      <button type="submit" name="button">Post</button>
      <a href="{% url 'secrets:popular' %}">Most Popular Secrets</a>
      {% for message in messages %}
      <p{% if message.tags %} class="{{ message.tags }}"{% endif %} style="color:red;">{{ message }}</p>
      {% endfor %}
    </form>
    <br>
    Recent Secrets...
    {% for secret in secrets %}
      <p>{{secret.secret}} {{secret.created_at}}
        ({{secret.secret_like.count}} likes)
        {% if secret.user_id.id == user.id %}
          <a href="{% url 'secrets:delete' secret.id %}">Delete</a>
        {% else %}
          {% if user in secret.secretlikes %}
            You liked this!
          {% else %}
            <a href="{% url 'secrets:like' secret.id %}">Like</a>
          {% endif %}
        {% endif %}
      </p>
    {% endfor %}
  </body>
</html>

apps/secrets/templates/secrets/popular.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Most Popular Secrets</title>
  </head>
  <body>
    Most Popular Secrets...
    <a href="{% url 'secrets:welcome' %}">Back</a>
    {% for secret in secrets %}
      <p>{{secret.user_id}} {{secret.secret}} {{secret.created_at}}
        ({{secret.secret_like.count}} likes)
        {% if secret.user_id.id == user.id %}
          <a href="{% url 'secrets:delete' secret.id %}">Delete</a>
        {% else %}
          {% if user in secret.secretlikes %}
            You liked this!
          {% else %}
            <a href="{% url 'secrets:like' secret.id %}">Like</a>
          {% endif %}
        {% endif %}
      </p>
    {% endfor %}
  </body>
</html>